## Index method 

GET http://localhost:3000/api/jokes

### Successfully posts a joke 

POST http://localhost:3000/api/jokes
Content-Type: application/json

{
    "category_id": 1,
    "body": "The furniture store keeps calling me to come back but I want is a one night stand"
}

### unsuccesfully posts a joke

POST http://localhost:3000/api/jokes
Content-Type: application/json

{
    "body": "The furniture store keeps calling me to come back but I want is a one night stand"
}

### show joke id: 1

GET http://localhost:3000/api/jokes/1

### unsucceffuly show joke id: 1000
GET http://localhost:3000/api/jokes/1000


### Successfully update joke 1 

PUT http://localhost:3000/api/jokes/1
Content-Type: application/json

{
    "body": "A programming joke",
    "category_id": 2
}

### Succesfully delete joke with id 1

DELETE http://localhost:3000/api/jokes/1


## Random Joke 

GET http://localhost:3000/api/jokes/random?category=great
















