## Index method 

GET http://localhost:3000/api/jokes

### Successfully posts a joke 

POST http://localhost:3000/api/jokes
Content-Type: application/json
Authorization: Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjU1NTg4NjUsInN1YiI6M30.532LzWGVAd9kY26atyIztvMBpe8-A7Y6yXSY027Ca2A

{
    "category_id": 1,
    "body": "The furniture store keeps calling me to come back but I want is a one night stand"
}

### unsuccesfully posts a joke

POST http://localhost:3000/api/jokes
Content-Type: application/json

{
    "body": "The furniture store keeps calling me to come back but I want is a one night stand"
}

### show joke id: 1

GET http://localhost:3000/api/jokes/1

### unsucceffuly show joke id: 1000
GET http://localhost:3000/api/jokes/1000


### Successfully update joke 1 

PUT http://localhost:3000/api/jokes/1
Content-Type: application/json
Authorization: Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjU1NTk4NTIsInN1YiI6MX0.eW3qHqsNP3XdNZI0Xn11Y3-4kJfaSdFT4oyjAlzSgGE

{
    "body": "A programming joke",
    "category_id": 2
}

### Succesfully delete joke with id 1

DELETE http://localhost:3000/api/jokes/1


### Destroy Joke I have permission for 


DELETE http://localhost:3000/localhost:3000/api/jokes/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjU1NTk4NTIsInN1YiI6MX0.eW3qHqsNP3XdNZI0Xn11Y3-4kJfaSdFT4oyjAlzSgGE


## Random Joke 

GET http://localhost:3000/api/jokes/random?category=great

### Create User 

POST http://localhost:3000/api/auth/sign_up 
Content-Type: application/json

{
    "username": "Henry3",
    "email": "henry3@test.com",
    "password": "password2",
    "password_confirmation": "password2"
}


### Sign in with correct details 

POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
    
    "email": "henry@test.com",
    "password": "password1"
   
}
### Sign in with correct details 

POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
    
    "email": "henry2@test.com",
    "password": "password2"
   
}




































